---
title: "More Resources"
output: 
  html_document:
    theme: lumen
    highlight: tango
    toc: true
    toc_float: 
      collapsed: true
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Last updated 10/31/2017*

***

There are many resources for self-guided study. Check back here for updates! If you have suggestions or recommendations, please reach out to kda-club@kellogg.northwestern.edu

## Stats Refreshers

Because DECS-430/431 was so long ago...

  * [Linear Regression](http://setosa.io/ev/ordinary-least-squares-regression/): cool, beautiful site that explains linear regression and ordinary least squared estimates! They have other awesome explanations but for really wonky statistical stuff (aside from PCA).
  * [Linear & Logistic Regression](http://r-statistics.co/Linear-Regression.html): good, general statistics knowledge

## Northwestern Resources

NU access required - check these out while you still have Northwestern student privileges! 

  * [Tableau License](https://www.tableau.com/academic/students): FREE Tableau license for students!
  * [DataCamp](http://www.it.northwestern.edu/research/campus-events/data-camp.html): AWESOME online courses for R, Python, and SQL. HIGHLY recommended for the programming basics and has stuff for more advanced topics. Follow the instructions from this NU site to get access to the advanced topics. Access has to be refreshed on a quarterly basis. 
  * [Northwestern R User Group](https://northwestern-r-users.github.io): Lots of good resources for R here from all the NU programs. Monthly classroom sessions on rotating topics. Sign up for the list-serve to get notifications. 
  * [Northwestern IT Training & Events](http://www.it.northwestern.edu/research/campus-events/index.html): Check back here for live workshops on Python & R
  * [Lynda](http://www.northwestern.edu/hr/workplace-learning/lynda/): Follow instructions at this link to get access to Lynda, a platform where instructors host video trainings (think Udemy, Udacity, and Khanh Academy)

## Cheat Sheets

Forgot what the command for klincom was? No worries, check out these handy one-pagers with function descriptions!

  * [STATA](https://geocenter.github.io/StataTraining/portfolio/01_resource/)
  * [R](https://www.rstudio.com/resources/cheatsheets/)
  * [Python](https://ehmatthes.github.io/pcc/cheatsheets/README.html)
  * [Numpy, Pandas, Keras, & MatPlotLib for Python](https://medium.com/towards-data-science/top-6-cheat-sheets-novice-machine-engineers-need-5ea43d1be3de)

## Example Problems and Walkthroughs

The best way to learn is to follow other peoples' work. Furthermore, there are SO many ways to do the same thing, and sometimes this is the best way to pick up new techniques. 

  * [Linear Regression in Python for Bay Area Home Prices](https://medium.com/towards-data-science/linear-regression-in-python-predict-the-bay-areas-home-price-5c91c8378878)
  * [Exploring Toronto Crime Data in Python](https://medium.com/towards-data-science/exploring-clustering-and-mapping-torontos-crimes-96336efe490f)

## Analytics Best Practice

  * [Charting](https://medium.com/towards-data-science/the-dos-and-don-ts-of-chart-making-13c629456027)
  * [Google Style Guide for R](https://google.github.io/styleguide/Rguide.xml): Because you are producing code for others to see, you should make sure that it is readable. This means adding plenty of comments to your code to explain what you are doing and following style guidelines.
  * [Google Style Guide for Python](https://google.github.io/styleguide/pyguide.html): Because you are producing code for others to see, you should make sure that it is readable. This means adding plenty of comments to your code to explain what you are doing and following style guidelines.

## Analytics Blogs and Newsletters

* [FiveThirtyEight.com](http://fivethirtyeight.com/)
* [Infogram Data Visualizations](https://infogram.com/blog/category/data-visualization/)
* [MachineLearnings](https://machinelearnings.co/)

## Specific Tool Training 

You'll generally find basic training under the Lynda or DataCamp links, but we'll post tool-specific trainings in this section.

### Excel

  * [Chandoo](https://chandoo.org/wp/): Learn to become an Excel ninja! This site aggregates cool, advanced visualization techniques and programming in Excel. 
  * [Everything by Jorge Camoes](https://excelcharts.com/author/jorge-camoes/): This guy is an excel viz ninja. Check out his stuff! 

### Tableau
All students have access to a free year of Tableau under their academic license

* [Free Tableau Download for Students](https://www.tableau.com/academic/students)

Tableau offers an amazing array of self-guided lessons and tutorials for new and advanced users of the tool

  * [Tableau training](https://www.tableau.com/learn/training)
  * [Tristan Guillevin](https://public.tableau.com/profile/guillevin#!/): This guy won the most recent Tableau viz competition! 

### SQL
SQL is the basic tool used to grab and analyze data from traditional databases. Some resources to get you up to speed quickly

* [Learn SQL | Codecademy](https://www.codecademy.com/learn/learn-sql)
* [Managing Big Data with MySQL | Coursera](https://www.coursera.org/learn/analytics-mysql)

### Python

#### Visualization

  * [The Ultimate Python Seaborn Tutorial: Gotta Catch ‘Em All](https://elitedatascience.com/python-seaborn-tutorial): Seaborn is an interface for matplotlib that arguably makes your visuals 10x better.

### R
#### Getting Started
R is a free, open source tool available for data scientists, business analysts, and everyone in between. You'll need two things to get started:
  * [Download R](https://cran.rstudio.com/): this is the core package that will let you run and test R packages
  * [Download R Studio](https://www.rstudio.com/products/rstudio/download/#download): this is a great user interface to R that makes it easier to quickly test and deploy R scripts

#### General Resources
These are some recommended resources in order to quickly self-learn and get up to speed:

  * [CodeSchool R Tutorial](https://www.codeschool.com/courses/try-r) : An online interactive tutorial that requires no downloads and will walk you through the basics of data analysis in R. Great for beginners and people completely new to the tool.
  * [R for Data Science](http://r4ds.had.co.nz/index.html): A complete online book about using R for data science. This covers all the basics of data science, as well as providing complete examples and demos
  * [swirl](http://swirlstats.com/): swirl is actually a package in R that teaches you how to program and fundamentals of data science within your console. If you want to learn R, or even brush up on your skills, try it out.

#### ggplot
  
ggplot isi the de-facto charting library for programming languages (you'll also find it for Python). It stands for Grammar of Graphics and is a way of creating pretty charts.   
  
  * [Official site](http://www.r-graph-gallery.com/portfolio/ggplot2-package/)
  * [ggplot tutorials](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html): 

#### Tidyverse

Tidyverse is a collection of libraries for R designed for data science. It's a heavily used library and you should definitely be familiar with it. 

  *[Official site](https://www.tidyverse.org)
  
  [An introduction to data cleaning with R](https://cran.r-project.org/doc/contrib/de_Jonge+van_der_Loo-Introduction_to_data_cleaning_with_R.pdf)

#### Other
  
  * [Correlation Matrix](http://www.sthda.com/english/wiki/correlation-matrix-a-quick-start-guide-to-analyze-format-and-visualize-a-correlation-matrix-using-r-software)
  * [Correlation cont](http://www.sthda.com/english/wiki/visualize-correlation-matrix-using-correlogram)
  * [Clustering](http://www.sthda.com/english/articles/25-cluster-analysis-in-r-practical-guide/111-types-of-clustering-methods-overview-and-quick-start-r-code/)
  

  
